import Head from 'next/head';
import { IoIosArrowDown, IoIosArrowForward } from 'react-icons/io';
import { AiOutlineArrowLeft } from 'react-icons/ai';
import { BiHash } from 'react-icons/bi';
import { useRouter } from 'next/router';





export default function Home() {

  const router = useRouter();
  const currentRoute = router.pathname;

  return (
    <div className='h-full  bg-slate-600 '>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className='flex items-center justify-center h-screen  '>
        <div className="h-full w-full md:h-4/5 md:w-3/4  rounded-xl bg-zinc-600 shadow-zinc-900 shadow-2xl">
          <div className="w-full h-6 rounded-t-lg  bg-[#282b30] z-50">
            <p className='text-slate-200 font-extrabold text-xs ml-2 pt-1 z-50'>DISCORD</p>
          </div>
          <div className="xl:hidden flex items-center justify-center h-screen">
            <h1 className='text-white text-2xl font-bold'>Only for Large screens</h1>
          </div>
          <div className="flex lg:h-[717px] w-full rounded-b-xl">
            <div className="hidden xl:flex xl:flex-col xl:h-[722px] w-1/5  rounded-bl-lg bg-[#36393e] px-2">
              <div className="w-full pl-2 h-12 flex justify-start items-center border-[#282b30] border-b-2">
                <h1 className='text-white font-bold text-xl cursor-pointer'>My Portfolio</h1>
              </div>
              <div className="w-full pl-2 h-12 flex justify-start items-center">
                <div className="text-zinc-300 mr-1 cursor-pointer"><IoIosArrowDown /></div><h1 className='text-zinc-300 font-semibold text-sm cursor-pointer'>CANALI TESTUALI</h1>
              </div>

              <div onClick={() => { router.push('/') }} className="w-full pl-2 h-12 flex justify-start cursor-pointer items-center rounded-lg  transition-all ease-out duration-300  hover:scale-105 active">
                <div className=" text-zinc-300 text-xl mr-1"><BiHash /></div><a href="#home" className=' text-zinc-300 font-semibold cursor-pointer hover:text-white '>Home</a>
              </div>

            
                <div onClick={() => { router.push('/about') }} className="w-full pl-2 h-12 flex justify-start cursor-pointer items-center rounded-lg transition-all ease-out duration-300 hover:bg-zinc-600 hover:scale-105 ">
                  <div className=" text-zinc-300 text-xl mr-1"><BiHash /></div><a href="#about" className=' text-zinc-300 font-semibold cursor-pointer hover:text-white'>About</a>
                </div>
             
              <div onClick={() => { router.push('/skills') }} className="w-full pl-2 h-12 flex justify-start cursor-pointer items-center rounded-lg transition-all ease-out duration-300 hover:bg-zinc-600 hover:scale-105 ">
                <div className=" text-zinc-300 text-xl mr-1"><BiHash /></div><a href="#skills" className=' text-zinc-300 font-semibold cursor-pointer hover:text-white'>Skills</a>
              </div>
              <div onClick={() => { router.push('/contact') }} className="w-full pl-2 h-12 flex justify-start cursor-pointer items-center rounded-lg transition-all ease-out duration-300 hover:bg-zinc-600 hover:scale-105">
                <div className=" text-zinc-300 text-xl mr-1"><BiHash /></div><a href="#contact" className=' text-zinc-300 font-semibold cursor-pointer hover:text-white'>Contact</a>
              </div>

              <div className="w-full pl-2 h-12 flex justify-start items-center mt-5 cursor-pointer">
                <div className=" text-zinc-300 mr-1 cursor-pointer"><IoIosArrowForward /></div><h1 className='cursor-pointer text-zinc-300 font-semibold text-sm'>CANALI VOCALI</h1>
              </div>
            </div>
            
            <div className=" hidden  xl:flex xl:flex-col xl:h-[722px] px-2 w-4/5 rounded-br-lg bg-[#424549]">
              <div className="w-full pl-2 h-12 flex justify-start items-center border-[#282b30] border-b-2">
                <div className="text-zinc-300 text-xl mr-1"><BiHash /></div><h2 className='text-zinc-300 font-semibold cursor-pointer hover:text-white'>Home</h2>
              </div>

              <section className='flex flex-col justify-center items-center mt-10'>
                <p className='text-2xl text-white'>Salve, mi chiamo Francesco, e questo è un mio portfolio in stile Discord.</p>
                <div className="flex items-center justify-center mt-14"><div className="text-2xl text-slate-100 mt-14 mr-2"><AiOutlineArrowLeft /></div><p className='text-xl text-slate-100 mt-14'>Clicca sulle sezioni a sinistra per saperne di più..</p></div>
              </section>

              <footer className='fixed top-[810px] left-1/2 text-center font-thin text-zinc-400'>Made with NEXTJS and TAILWIND |30/01/2023|</footer>
            </div>
          </div>


        </div>
      </div>


    </div>
  )
}
